config/routes.rb
Rails.application.routes.draw do

  get "/", to: "purchase#index"
  post "/", to: "purchase#create"
  get "/:id", to: "purchase#delete", as: :delete
  get "/total/:id", to: "purchase#monthly_total", as: :total

end

app/models/food.rb
class Food < ActiveRecord::Base
  validates :item, :cost, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController

  def index
    @foods = Food.all
  end

  def create
    @food = Food.new
    @food.item = params[:item]
    @food.cost = params[:cost]
    @food.description = params[:description]
    @food.vendor = params[:vendor]
    @food.created_at = params[:created_at]
    if @food.save
      redirect_to "/"
    else
      @foods = Food.all
      render :index
    end
  end

  def delete
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to "/"
  end

  # def monthly_total
  #   raise ArgumentError, params[:id]
  #   @foods = Food.all
  #   total_hash = Food.group("DATE_TRUNC('month', created_at)").sum(:cost)
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodPurchases</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/purchase/index.html.erb
<div class="tracker">
  <div class="layer">

    <h1>Food Purchase Tracker</h1>

    <div class="errors">
      <% if @food %>
          <% @food.errors.each do |column, error| %>
            <li><%= column.capitalize %> <%= error %></li>
          <% end %>
      <% end %>
    </div>

    <div class="form">
      <%= form_tag "/", method: :post do %>
        <%= text_field_tag :item, "", class: "text_field", placeholder: "Food Item" %>
        <%= text_field_tag :cost, "", class: "text_field", placeholder: "Food Cost" %>
        <%= text_field_tag :description, "", class: "text_field", placeholder: "Food Description" %>
        <%= text_field_tag :vendor, "", class: "text_field", placeholder: "Food Vendor" %>
        <%= submit_tag "Add Food Purchase" %>
      <% end %>
    </div>

    <div class="food_table">
      <table>
        <tr>
          <th>Food Item</th>
          <th>Cost</th>
          <th>Description</th>
          <th>Vendor</th>
          <th>Date</th>
          <th></th>
        </tr>

      <% @foods.each do |food| %>
        <tr>
          <td><%= food.item %></td>
          <td><%= number_to_currency(food.cost) %></td>
          <td><%= food.description %></td>
          <td><%= food.vendor %></td>
          <td><%= food.created_at.strftime("%A, %B %e, %Y") %></td>
          <td><%= link_to "Delete Entry", delete_path(food), class: "link_to_color", method: :get, data: { confirm: "Delete food entry?" } %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <div class="total_table">
      <table>
        <tr>
          <th>Cost Total</th>
          <!-- <th></th> -->
        </tr>

      <% total = 0
         @foods.each do |food|
           total += food.cost
         end %>
        <tr>
          <td><%= total %></td>
          <!-- <td><%=  %></td> -->
        </tr>
      </table>
    </div>

    <!-- <div class="monthly_total">
      <%= select_tag :month, options_for_select(["None", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]) %>
      <%= link_to "Delete Entry", total_path(:month), class: "link_to_color", method: :get %>
    </div> -->

  </div>
</div>